version: '3.7'


services:

  erfa_data_prod:
    image: postgres:14.1-alpine
    restart: always
    hostname: postgres
    ports:
      - 5777:5432
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: Qwer!234
      POSTGRES_DB: ProductionManagement
    healthcheck:
          test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
          interval: 30s
          timeout: 60s
          retries: 5
          start_period: 80s
