
name: PROD_RELEASE

on:
  push:
    branches: [ "main" ]


jobs:
  dev_build:
     runs-on: ubuntu-latest
     name: dev_build
     steps:
     - uses: actions/checkout@v3
       with:
             fetch-depth: 0
     - name: Setup .NET
       uses: actions/setup-dotnet@v3
       with:
         dotnet-version: 7.0.x
     - name: Restore dependencies
       run: dotnet restore
  
     - name: Build
       run: dotnet build --no-restore

     - name: Test
       run: dotnet test --no-build --verbosity normal
             
     - name: Get Current Version
       id: get_version
       run: | 
          STR=$(git describe --abbrev=0 --tags)
          echo ::set-output name=version::${STR:1}
          echo ${STR:1}


     - name: Build and Push Docker Image
       uses: mr-smithers-excellent/docker-build-push@v6
       with:
         tags: ${{  steps.get_version.outputs.version }}
         image: ${{ secrets.DOCKER_USERNAME }}/erfa-production
         registry: docker.io
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
